[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q
filterwarnings =
	ignore::DeprecationWarning:pytest_asyncio.plugin
	ignore::DeprecationWarning:pydantic_core.core_schema
	ignore::DeprecationWarning:fastapi.openapi.models
